### ISSUE TITLE
Can't Connect to Mysql

### ISSUE THREAD

**Issue by jsl303** [naveed125/docker-lemp-app#1]
When I try to install wordpress, it says "Error establishing a database connection".
This is what I filled out in the setup page.
Database Name: appdb
Username: appuserdb
Password: p@ssw0rd!
Database Host: localhost

**Comment by naveed125** [comment]
Are you installing wordpress inside the docker container or outside on your machine? If its outside then wordpress wont be able to connect to the local database unless you export the ports. At any rate you may consider this guide for settings up a local wordpress environment using docker: https://medium.com/@naveed125/how-to-create-a-massively-scalable-wordpress-cluster-almost-for-free-d1a9e4c79ab5

**Comment by jsl303** [comment]
Yes, I'm installing inside the container.
It looks like Wordpress inside nginx container cannot reach mysql 
container as localhost.
Maybe docker-compose.yml or Dockerfile need to be modified so that nginx 
container can reach mysql port in mysql container.

**Comment by naveed125** [comment]
Use the host name "db" if you are running in the container.
